### ISSUE TITLE
DiskStation DS223j doesn't work

### ISSUE THREAD

**Issue by avaskakto** [007revad/Synology_CPU_temperature#16]
Synology_CPU_temp v2.3.7
DS223j DSM 7.2.1-69057-5 

DSM shutdown Temp:  105°C  221°F
./syno_cpu_temp.sh: line 383: show__temps: command not found

**Comment by 007revad** [comment]
What does the following command return?
```
grep 'vendor_id' /proc/cpuinfo
```

**Comment by avaskakto** [comment]
Nothing

```
ivanich@nas223j:~$ grep 'vendor_id' /proc/cpuinfo
ivanich@nas223j:~$ grep -E '^model name' /proc/cpuinfo
ivanich@nas223j:~$ grep -E '^Processor' /proc/cpuinfo
ivanich@nas223j:~$ grep . /sys/class/hwmon/hwmon*/temp*_max
grep: /sys/class/hwmon/hwmon*/temp*_max: No such file or directory
ivanich@nas223j:~$ grep . /sys/class/hwmon/hwmon*/temp*_crit
grep: /sys/class/hwmon/hwmon*/temp*_crit: No such file or directory
ivanich@nas223j:~$ cat /sys/class/hwmon/hwmon0/device/temp1_max
cat: /sys/class/hwmon/hwmon0/device/temp1_max: No such file or directory
ivanich@nas223j:~$ 
```

**Comment by 007revad** [comment]
What do these commands return:
```
cat /proc/cpuinfo | head -19
```
```
ls /sys/class/hwmon
```
```
ls /sys/class/hwmon/hwmon0
```
```
ls /sys/class/hwmon/hwmon1
```

**Comment by avaskakto** [comment]
`ivanich@nas223j:~$ cat /proc/cpuinfo | head -19
processor	: 0
BogoMIPS	: 54.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x2
CPU part	: 0xd05
CPU revision	: 0

processor	: 1
BogoMIPS	: 54.00
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x2
CPU part	: 0xd05
CPU revision	: 0

processor	: 2
ivanich@nas223j:~$ ls /sys/class/hwmon
ivanich@nas223j:~$ ls /sys/class/hwmon/hwmon0
ls: cannot access '/sys/class/hwmon/hwmon0': No such file or directory
ivanich@nas223j:~$ ls /sys/class/hwmon/hwmon1
ls: cannot access '/sys/class/hwmon/hwmon1': No such file or directory
ivanich@nas223j:~$`

**Comment by 007revad** [comment]
What about these:
```
ls /sys/class/thermal
```
```
ls /sys/class/thermal/thermal_zone0
```
```
ls /sys/class/thermal/thermal_zone1
```
```
ls /sys/class/thermal/thermal_zone2
```
```
ls /sys/class/thermal/thermal_zone3
```

**Comment by avaskakto** [comment]
```
ivanich@nas223j:~$ ls /sys/class/thermal
thermal_zone0
ivanich@nas223j:~$ ls /sys/class/thermal/thermal_zone0
available_policies  k_po    policy     sustainable_power  trip_point_0_type  trip_point_2_hyst  uevent
integral_cutoff     k_pu    power      temp               trip_point_1_hyst  trip_point_2_temp
k_d                 mode    slope      trip_point_0_hyst  trip_point_1_temp  trip_point_2_type
k_i                 offset  subsystem  trip_point_0_temp  trip_point_1_type  type
ivanich@nas223j:~$ ls /sys/class/thermal/thermal_zone1
ls: cannot access '/sys/class/thermal/thermal_zone1': No such file or directory
ivanich@nas223j:~$ ls /sys/class/thermal/thermal_zone2
ls: cannot access '/sys/class/thermal/thermal_zone2': No such file or directory
ivanich@nas223j:~$ ls /sys/class/thermal/thermal_zone3
ls: cannot access '/sys/class/thermal/thermal_zone3': No such file or directory
ivanich@nas223j:~$
```

**Comment by 007revad** [comment]
We're close. Can you try this one.
```
for i in /sys/class/thermal/thermal_zone0/*; do echo -n "$(basename -- "$i")  " && cat "$i"; echo; done
```

**Comment by avaskakto** [comment]
```
ivanich@nas223j:~$ for i in /sys/class/thermal/thermal_zone0/*; do echo -n "$(basename -- "$i")  " && cat "$i"; echo; done
available_policies  user_space step_wise 

integral_cutoff  0

k_d  0

k_i  0

k_po  0

k_pu  0

mode  enabled

offset  0

policy  step_wise

power  cat: /sys/class/thermal/thermal_zone0/power: Is a directory

slope  1

subsystem  cat: /sys/class/thermal/thermal_zone0/subsystem: Is a directory

sustainable_power  0

temp  35366

trip_point_0_hyst  0

trip_point_0_temp  120000

trip_point_0_type  critical

trip_point_1_hyst  0

trip_point_1_temp  90000

trip_point_1_type  passive

trip_point_2_hyst  0

trip_point_2_temp  105000

trip_point_2_type  passive

type  cpu-thermal

uevent  DEVNAME=thermal_zone0

ivanich@nas223j:~$ 
```

**Comment by 007revad** [comment]
Perfect.

Give me a few hours and I'll update the script to support the DS223j's Realtek RTD1619B CPU.

**Comment by 007revad** [comment]
So I can more easily identify the CPU can you tell me what this command retruns?
```
synogetkeyvalue /etc.defaults/synoinfo.conf unique
```

**Comment by avaskakto** [comment]
ivanich@nas223j:~$ synogetkeyvalue /etc.defaults/synoinfo.conf unique

**synology_rtd1619b_ds223j**

**Comment by 007revad** [comment]
Can you try this version of the script.
https://github.com/007revad/Synology_CPU_temperature/releases/tag/v2.3.8-RC 

And let provide a screenshot of the out put. And a copy of the log if you have logging enabled.

**Comment by avaskakto** [comment]
![20240721_142116](https://github.com/user-attachments/assets/42e7d6f7-f4d2-4417-add1-13eb3ad4dd42)


log:
```
Synology_CPU_temp v2.3.7
DS223j DSM 7.2.1-69057-5.
Unknown CPU model
DSM shutdown Temp:  105°C  221°F

```

**Comment by 007revad** [comment]
Sorry. Try this one https://github.com/007revad/Synology_CPU_temperature/releases/tag/v2.3.9-RC

And provide a screenshot of the output. And a copy of the log if you have logging enabled.

**Comment by avaskakto** [comment]
![160827](https://github.com/user-attachments/assets/2f8cfa9b-459a-4d4d-b654-bcc27efae8cb)


log:
```
Synology_CPU_temp v2.3.8
DS223j DSM 7.2.1-69057-5 
rtd1619b
DSM shutdown Temp:  105°C  221°F

2024-07-21 16:10:05 - cpu-thermal:  36.005°C   96.8°F

```

**Comment by 007revad** [comment]
Excellent.

**Comment by avaskakto** [comment]
I think you can close. Thanks a lot!!!

**Comment by 007revad** [comment]
I've released the new version as a full release. https://github.com/007revad/Synology_CPU_temperature/releases
