### ISSUE TITLE
intel Atom CPU's not displaying any cores

### ISSUE THREAD

**Issue by blakeusblade** [007revad/Synology_CPU_temperature#18]
Running the script on (at least my one of my syno boxes with an Atom CPU) doesn't display current CPU core temps...

log output is below...

Synology_CPU_temp v2.3.8
DS1517+-j DSM 7.2.2-72806 
Intel(R) Atom(TM) CPU C2538 @ 2.40GHz
DSM shutdown Temp:  95°C   203°F

**Comment by 007revad** [comment]
Via SSH what do these commands return: 
```
ls /sys/bus/platform/devices/coretemp.0/hwmon/hwmon0/device
```
and
```
ls /sys/class/hwmon/hwmon0
```

**Comment by blakeusblade** [comment]
> Via SSH what do these commands return:
> 
> ```
> ls /sys/bus/platform/devices/coretemp.0/hwmon/hwmon0/device
> ```
> 
> and
> 
> ```
> ls /sys/class/hwmon/hwmon0
> ```
> 
> and
> 
> ```
> ls /sys/class/hwmon/hwmon0/device
> ```

Command requested to run: ls /sys/bus/platform/devices/coretemp.0/hwmon/hwmon0/device
Output: 
driver    name       temp2_crit        temp2_label  temp3_crit_alarm  temp3_max         temp4_input  temp5_crit        temp5_label
hwmon     power      temp2_crit_alarm  temp2_max    temp3_input       temp4_crit        temp4_label  temp5_crit_alarm  temp5_max
modalias  subsystem  temp2_input       temp3_crit   temp3_label       temp4_crit_alarm  temp4_max    temp5_input       uevent

Command requested to run: ls /sys/class/hwmon/hwmon0
Output:
device  power  subsystem  uevent

Command requested to run: ls /sys/class/hwmon/hwmon0/device
Output:
driver    name       temp2_crit        temp2_label  temp3_crit_alarm  temp3_max         temp4_input  temp5_crit        temp5_label
hwmon     power      temp2_crit_alarm  temp2_max    temp3_input       temp4_crit        temp4_label  temp5_crit_alarm  temp5_max
modalias  subsystem  temp2_input       temp3_crit   temp3_label       temp4_crit_alarm  temp4_max    temp5_input       uevent

**Comment by 007revad** [comment]
I see the problem. 

The output of those commands are the same as my old DS1812+ with DSM 6. But different to my DS720+ with DSM 7. I assumed DSM 6 was different to DSM 7. But it's clear now that the difference is CPU architecture specific.

I should a fixed version of the script available today.

**Comment by 007revad** [comment]
This new v2.3.9 should work for you now.
https://github.com/007revad/Synology_CPU_temperature/releases

**Comment by blakeusblade** [comment]
> This new v2.3.9 should work for you now. https://github.com/007revad/Synology_CPU_temperature/releases

Excellent! It works now... Great work and thanks heaps!

`DS1517+-j DSM 7.2.2-72806 
synology_avoton_1517+
Logging to /volume1/CPUTemp/logs

Intel(R) Atom(TM) CPU C2538 @ 2.40GHz
DSM shutdown Temp:  95°C   203°F

Core 0: 47°C  116.6°F
Core 1: 46°C  114.8°F
Core 2: 46°C  114.8°F
Core 3: 46°C  114.8°F`
