### ISSUE TITLE
Does not work witn Intel Pentium D

### ISSUE THREAD

**Issue by jjvelar** [007revad/Synology_CPU_temperature#7]
Hi, thanks for your work. Much appreciated.

I tried and the script does not get the temperature for my Intel Pentium D on a DSM923+ with DSM 7.2.1.

Please, advise.

![image](https://github.com/007revad/Synology_CPU_temperature/assets/47498098/40a79c5e-4ce6-4823-a95d-5b62835c4606)

**Comment by 007revad** [comment]
What do these 2 commands return?
```
ls /sys/class/hwmon/hwmon0

ls /sys/bus/platform/devices/coretemp.0
```

**Comment by jjvelar** [comment]
Here you've got it:

![image](https://github.com/007revad/Synology_CPU_temperature/assets/47498098/b8d33d12-7474-4c59-8b9c-91f90f3e5f1f)

**Comment by 007revad** [comment]
Thanks. I see the problem. I assumed all Intel CPUs would have tempX_label and tempX_max.

Thankfully tempX_crit is the same as tempX_max so I can use tempX_crit instead. And I can work around the missing tempX_label

Can you tell me what this command returns:
```
grep . /sys/class/hwmon/hwmon*/* 2>/dev/null
```

**Comment by 007revad** [comment]
Try this version: 
https://github.com/007revad/Synology_CPU_temperature/releases/tag/v2.1.4

**Comment by jjvelar** [comment]
works like a charm. Thanks!

![image](https://github.com/007revad/Synology_CPU_temperature/assets/47498098/04b33b13-71a7-49e2-b90c-72c93fa1f8b5)
